// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tftkkfdlogstaxckbjgz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRmdGtrZmRsb2dzdGF4Y2tiamd6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMDA4MzIsImV4cCI6MjA2Mzc3NjgzMn0.fSPETwgz4C8FPysevKvwT7QgTZtT2yazPJyPQ77UUck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);